export const ROUTES = {
  home: "/",
  dashboard: "/dashboard",
  dashboardFlipbook: "/dashboard/flipbook",
  dashboardCreateFlipbook: "/dashboard/create-flipbook",
  dashboardPlans: "/dashboard/plans",
  dashboardUsers: "/dashboard/users",
  dashboardOrders: "/dashboard/orders",
  flipbookView: (flipId) => `/flipbook-view/${flipId}`,
  privacy: "/privacy",
  terms: "/terms",
  refund: "/refund",
  login: "/?login=1",
  resetPassword: "/reset-password",
};
